---
title: "2.4 The Monty Hall Problem"
output: html_notebook
---

####Python Code

```{python, eval = FALSE}
"""This file contains code for use with "Think Bayes",
by Allen B. Downey, available from greenteapress.com

Copyright 2012 Allen B. Downey
License: GNU GPLv3 http://www.gnu.org/licenses/gpl.html
"""

from thinkbayes import Pmf


class Monty(Pmf):
    """Map from string location of car to probability"""

    def __init__(self, hypos):
        """Initialize the distribution.

        hypos: sequence of hypotheses
        """
        Pmf.__init__(self)
        for hypo in hypos:
            self.Set(hypo, 1)
        self.Normalize()

    def Update(self, data):
        """Updates each hypothesis based on the data.

        data: any representation of the data
        """
        for hypo in self.Values():
            like = self.Likelihood(data, hypo)
            self.Mult(hypo, like)
        self.Normalize()

    def Likelihood(self, data, hypo):
        """Compute the likelihood of the data under the hypothesis.

        hypo: string name of the door where the prize is
        data: string name of the door Monty opened
        """
        if hypo == data:
            return 0
        elif hypo == 'A':
            return 0.5
        else:
            return 1


def main():
    hypos = 'ABC'
    pmf = Monty(hypos)

    data = 'B'
    pmf.Update(data)

    for hypo, prob in sorted(pmf.Items()):
        print hypo, prob


if __name__ == '__main__':
    main()
```

####R Code

#####Monty class
The Monty 'class' defined here is a function that takes a vector of hypotheses
and returns a named vector of equal probablities.



```{r R Monty Class}
library(tidyverse, quietly = TRUE)

Normalize <- function(pmf){pmf / sum(pmf)}

Mult <- function(prior,hypo,likelihood){
  prior[hypo] * likelihood
}

#return a named vector of probabilities, names are the hypotheses
Monty <- function(hypos){
  
  require(dplyr)

    hypos %>%
      length() %>%
      rep(1, .) %>%
      `names<-`(hypos)  %>%
      Normalize()  
}



Likelihood <- function(data, hypo){
    if (hypo == data) {
      0
    } else if (hypo == "A") {
      0.5
    } else {
      1
    }
  
}

Update <- function(pmf, data){
  pmf %>%
    names() %>%
    vapply(Likelihood, c(like = 0.0), data = data) %>%
    mapply(Mult, hypo = names(pmf), likelihood = ., MoreArgs = list(prior = pmf),
           USE.NAMES = FALSE) %>%
    Normalize()
    }
```
#####Main
```{r main}
hypos  <-  LETTERS[1:3]

pmf <- Monty(hypos)

data <- "B"
pmf <- Update(pmf, data)

pmf
```
