---
title: "The train  problem"
output: html_notebook
---

```{r normalize}
normalize <- function(x) {
  #ensure  the values in the vector x add up to one
  x /sum(x)
  }
```
```{r mult}
mult <- function(prior,hypo,likelihood){
  prior[hypo] * likelihood
}
```

```{r update}
#Updates each hypothesis based on the data
update <- function(pmf, data){
    likelihoods <- vapply(names(pmf),likelihood, c(like = 0.0), data = data) 
    pmf <- mapply(mult,
                  hypo = names(pmf),
                  likelihood = likelihoods,
                  MoreArgs = list(prior = pmf),
                  USE.NAMES = FALSE) 
    normalize(pmf)
    }
```




```{r pmf constructor}
new_pmf <- function(hypos) {
# Represents a a probability mass function.
# return a named numeric vector of equal probabilities
# from a character vector of hypotheses, with class pmf   
       
      l <- length(hypos)
      pmf <- rep(1,l)
      names(pmf) <- hypos
      pmf <- normalize(pmf)
      structure(pmf, class = "pmf")
}

```
```{r pmf validator}
validate_pmf <- function(x){
  #more complex checking logic
  #check all names are unique
  if (anyDuplicated(names(x)) > 0) {
    stop(
      "All hypotheses must be unique",
      call. = FALSE
    )
  
  }
  x
}
```

```{r pmf helper}
pmf <- function(hypos) {
  validate_pmf(new_pmf(hypos))
}
```

The class defined above will be helpful in the futue but could be replaced by just functions.
Initial thoughts are that all that differs is the likelihood function for each class . Maybe I can just use S3 generics


```{r likelihood generic}
likelihood <- function(data, hypo, ...){
  UseMethod("likelihood")
}
```

```{r train class}
#Constructor
train_new <- function(x) {
# a character vector of class dice   
      stopifnot(is.numeric(x))
      structure(x, class = "dice")
}
#Validator
validate_train<- function(x){
  #complicated checks go here i.e. 
  x
}
#helper
train <- function(data){
  #public facing , todo: helpful errors
  validate_train(train_new(data))
}
likelihood.train <- local({
  #this is a technique known as memoizaiton. using global assignment (the <<- operator ) in this local namespace.

  function(data, hypo){
    hypo <- as.numeric(hypo)
      if (hypo < data) {
           0
            }
      else {
       1.0/hypo
      }
  
  }
})

```


```{r main}

hypos  <-  1:1000


train_pmf <- pmf(hypos)

data <- train(60)
train_pmf <- update(train_pmf, data)
plot(names(train_pmf),train_pmf)

#mean of posterior distribution
sum(hypos * train_pmf)
 
 
```
